### ISSUE TITLE
Errors in prepare_geoclim function

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/cdms.products#73]
@dannyparsons I am adding documentation to more functions and so running examples.

**prepare_geoclim_month**
Perhaps this is an error, or perhaps I'm doing something wrong. If I run the following code I get an error that 

` object 'month_abb_english' not found `

I cannot find in the data where `month_abb_english` is defined, so am not sure how to fix this one!

```
prepare_geoclim_month(data = daily_niger, year = "year", month = "month",
                   station_id = "station_name",
                   element = "rain", metadata = stations_niger, 
                   join_by = "station_name",
                   latitude = "lat", longitude = "long")
```

Also
1. Should this have an optional `date` parameter which `year` and `month` can be created from
2. Should this be `station` not `station_id`
3. What length argument can be given to `add_cols`? (`character(1)`?)

**I'm also getting an error in `prepare_geoclim`:**
If I run the following then I get an error

```
dekad_data <- daily_niger %>%
  dplyr::mutate(dekad = dekad(date))

prepare_geoclim(data = dekad_data, year = "year",
                station_id = "station_name",
                type_col = "dekad",
                element = "rain", metadata = stations_niger, 
                join_by = "station_name",
                latitude = "lat", longitude = "long")
```

**Comment by dannyparsons** [comment]
`month_abb_english` is defined in `constants.R`. Surprised if it doesn't find it in functions?

1. Yes, good idea.
2. The GeoCLIM documentation mentions "ID" https://github.com/IDEMSInternational/cdms.products/issues/17#issuecomment-1024256116 so I think keep it as ID.
3. `character`. It is for a set of additional station columns that you might want to include in the output, but not mandatory e.g. station elevation or country.

I can look into the error later if you still can't find the cause.
